### ISSUE TITLE
Open FUSE todo

### ISSUE THREAD

**Issue by orso82** [ProjectTorreyPines/FUSE.jl#597]
- [x] Register all packages with FuseRegistry @orso82 

- [x] Consistent formatting for all packages @orso82 

- [x] Add documentation build for all packages @orso82 

- [ ] Merge as many open PRs for the following repos
   - [ ] FUSE @ProjectTorreyPines/dreamteam 
   - [x] TGLFNN @orso82 
   - [x] EPEDNN @orso82 
   - [x] NNeutronics @orso82 

- [x] People should review NOTICE.md file of each package and change it as needed / wanted

- What to do for packages developed under FPP-ID IR&D? @jacksonharvey @daveweisberg 
   - [x] XSteamTP
   - [x] ThermalSystemModels --> to be made open

- [x] XSteam under PTP

- [ ] Fix undocumented exported functions:
   - [x] FiniteElementHermite @bclyons12 
   - [ ] IMAS @orso82 
   - [ ] MXHEquilibrium @bclyons12 @lstagner 
   - [x] VacuumFields @bclyons12 
   - [x] TEQUILA @bclyons12 
   - [ ] SimulationParameters @orso82 
   - [x] QED @bclyons12 
   - [ ] ADAS @jguterl 

- [ ] Fix regression tests
   - [x] VacuumFields.jl
   - [x] QED.jl
   - [ ] ThermalSystemModels.jl
   - [x] ADAS.jl

- [ ] (Ideally) Add runtests for the packages missing it
  - [x] TEQUILA

- [x] Move `generate_dd` to it's own private repository

- [x] `generate_dd` as a CI service of IMASDD

- [x] Use FuseUtils instead of Trapz package in MXHEquilibrium @bclyons12 

- [ ] Update all github workflows to use FuseRegistry
   - [ ] See https://github.com/ProjectTorreyPines/IMASDD.jl/blob/master/.github/workflows/make_docs.yml for example

- [x] Install FUSE from Manifest_CI.toml

- [x] Remove explicit dependency of sub-packages that resulted from using packages in dev mode

- [x] Bump most (all) packages versions to `1.x` so that install from registry can pick up minor releases updates

- [x] Will likely need a `make bump_versions branch=BLA` that bumps minor versions of packages that have a branch matching a certain name. To be used when we merge a FUSE PR.

- [ ] Finish writing paper
   - @TimSlendebroek to take most recent graphics and update what's on overleaf
   - To be submitted as Sherwood invited edition of PoP

- [ ] Do all above for new repos:
   - [ ] RABBIT (what do we do with the executables?)
   - [x] GenerateDD

- [x] Create FUSE discord server
    - @orso82 / @TimSlendebroek 

- [x] Logging of actors should be turned on by default

========

* try unpinning HDF5
