### ISSUE TITLE
Create sysimage on Omega

### ISSUE THREAD

**Issue by bclyons12** [ProjectTorreyPines/FUSE.jl#793]
I'm working to make a sysimage on Omega and I wanted a place to document best practices. So far I've found the following pitfalls:

1. There's currently some issue (https://github.com/JuliaLang/PackageCompiler.jl/issues/990, https://github.com/JuliaLang/PackageCompiler.jl/issues/963) with PackageCompiler.jl that makes it hang if the `JULIA_NUM_THREADS` environment variable is set. This is fixed by just having it unset when you run `create_sysimage()` in Julia. The compiled sysimage does then work if you do run with threads, though I see some compilation triggered.
2. The Omega login nodes and worker nodes have different architectures ([Intel and AMD, respectively](https://fusionga.sharepoint.com/sites/Computing/SitePages/Omega.aspx#pgf-compiler-considerations)). If you run `create_sysimage()`, it defaults the `cpu_target` kwarg to `native`, which means it's compiled only for the present cpu. That means a sysimage compiled on the login node won't run on the work node. This is fixed by running with `cpu_target="generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1)"`.

Currently I have done the following.
1. Created a `precompile_script.jl` that contains:
```
using FUSE
dd = IMAS.dd()
FUSE.warmup(dd)
```
2. In my default project, `] add PackageCompiler`.
3. Activate a new project and `] add FUSE`
4. Then run
```
using PackageCompiler
create_sysimage(["FUSE"], sysimage_path="./sys_fuse.so", precompile_execution_file="./precompile_script.jl", cpu_target="generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1)")
```
This takes roughly a half hour, with the `PackageCompiler: compiling incremental system image` step taking about 18 minutes.
5. Exit julia and relaunch with `julia -Jsys_fuse.so` 

I then get the following output.
**Login node, no sysimage** (`julia -t 10`):
```
julia> @time using FUSE
 18.973856 seconds (13.83 M allocations: 929.466 MiB, 5.68% gc time, 7.57% compilation time: 65% of which was recompilation)

julia> @time dd = IMAS.dd();
  1.824272 seconds (331.58 k allocations: 15.971 MiB, 5.35% gc time, 99.63% compilation time: 12% of which was recompilation)

julia> @time FUSE.warmup(dd);
...
701.555852 seconds (2.14 G allocations: 100.536 GiB, 3.58% gc time, 11 lock conflicts, 102.84% compilation time: <1% of which was recompilation)
```

**Login node, with sysimage** (`julia -t 10 -Jsys_fuse.so`):
```
julia> @time using FUSE
  0.000638 seconds (178 allocations: 13.031 KiB)

julia> @time dd = IMAS.dd();
  0.002888 seconds (12.49 k allocations: 512.281 KiB)

julia> @time FUSE.warmup(dd);
...
125.325021 seconds (315.80 M allocations: 9.990 GiB, 3.54% gc time, 16 lock conflicts, 9.10% compilation time)
```

**Worker node, without sysimage** (`julia -t 16`):
_Forthcoming_

**Worker node, with sysimage** (`julia -t 16 -Jsys_fuse.so`):
```
julia> @time using FUSE
  0.000708 seconds (178 allocations: 13.031 KiB)

julia> @time dd = IMAS.dd();
  0.003303 seconds (12.49 k allocations: 512.281 KiB)

julia> @time FUSE.warmup(dd);
...
267.756069 seconds (260.13 M allocations: 8.452 GiB, 2.87% gc time, 0.02% compilation time)

```

**Comment by bclyons12** [comment]
The above results use the `env/gcc11.x` module, and I set the `JULIA_CC` environment varaible to `/opt/rh/gcc-toolset-11/root/usr/bin/gcc -O2`. I think, by default, it will just use `gcc` which would resolve to the same executable but without any optimization flags.

**Comment by bclyons12** [comment]
### To-do list

- [ ] Test if creating the sysimage on the worker node improves performance
- [ ] Assess other compilation flags (e.g., -O3) for compilation speed and execution performance
- [ ] Use PrecompileTools.jl and SnoopCompile.jl to improve FUSE precompilation without sysimage.
We could potentially reduce the scope of the sysimage and offload some of this to FUSE's regular precompilation, particularly if we can speed some of that up by checking invalidations, etc.
- [ ] Determine why we see compilation when threaded sometimes
- [ ] Create `fuse` module on Omega that loads compatible julia, etc.  
<details>
<summary>ChatGPT suggested implementation</summary>
The most robust solution is to provide a stable, shared “base” environment and sysimage that all users can rely on, while allowing them to add their own separate, layered environments for their personal changes. Here’s how you can set this up:

1. **Create a Dedicated Base Environment**:  
   Set up a dedicated `Project.toml` and `Manifest.toml` in a shared, read-only location on the cluster. This base environment should include your `FUSE` package and all of its dependencies pinned to specific versions. By pinning the versions in the `Manifest.toml`, you ensure that the environment is fully reproducible.

2. **Build the Sysimage from the Base Environment**:  
   Use `PackageCompiler.jl` within this base environment to create a sysimage. This sysimage will contain precompiled code for `FUSE` and all its dependencies at the specified versions. By doing this once, you guarantee that everyone on the cluster who uses this environment and sysimage will enjoy fast startup times.

3. **Make the Base Environment and Sysimage Read-Only and Public**:  
   Place the base environment (the `Project.toml` and `Manifest.toml`) and the sysimage file in a globally accessible, read-only directory. This ensures that users cannot modify it. The sysimage should be referenced by setting `JULIA_SYSIMAGE` or by instructing users how to start Julia with the `--sysimage` option pointing to your compiled image.

4. **Use Load Path Stacking to Allow User Customization**:  
   Julia’s load path can include multiple environments. By setting `JULIA_LOAD_PATH` to start with the base environment’s path, users will, by default, get `FUSE` and all its dependencies from the stable, sysimage-backed environment. For example:
   ```sh
   export JULIA_LOAD_PATH="/path/to/shared/env:@:"
   ```
   This puts the shared environment first in the load path. The `@` and `:` entries allow users to create their own local environments (for example, in `~/.julia/environments`) that stack on top of the base environment.

5. **Users Add Packages in Their Own Environment**:  
   Since the shared environment is read-only and stable, users cannot modify it, which is by design. However, they can activate their own local environment (e.g., `Pkg.activate("~/.julia/environments/myenv")`) and add or change packages there. These personal environments will be layered on top of the base environment, allowing the user to override or add packages without touching the shared environment.

   Changes in the user’s personal environment won’t affect the base environment or the sysimage. Packages not included in the base environment won’t gain the startup speed benefits of the sysimage, but everything provided by the base environment will still be fast.

**Result**:  
With this approach, you lock down and precompile a known-good environment containing `FUSE` and its dependencies. All cluster users benefit from fast load times for those packages, while still retaining the freedom to customize their own environments by layering them above the shared base environment. This prevents version conflicts or accidental breakage in the public environment, ensures reproducibility, and gives users flexibility without granting them permission to alter the public base environment.
</details>

**Comment by bclyons12** [comment]
Recommendations from ChatGPT:

The most robust solution is to provide a stable, shared “base” environment and sysimage that all users can rely on, while allowing them to add their own separate, layered environments for their personal changes. Here’s how you can set this up:

1. **Create a Dedicated Base Environment**:  
   Set up a dedicated `Project.toml` and `Manifest.toml` in a shared, read-only location on the cluster. This base environment should include your `FUSE` package and all of its dependencies pinned to specific versions. By pinning the versions in the `Manifest.toml`, you ensure that the environment is fully reproducible.

2. **Build the Sysimage from the Base Environment**:  
   Use `PackageCompiler.jl` within this base environment to create a sysimage. This sysimage will contain precompiled code for `FUSE` and all its dependencies at the specified versions. By doing this once, you guarantee that everyone on the cluster who uses this environment and sysimage will enjoy fast startup times.

3. **Make the Base Environment and Sysimage Read-Only and Public**:  
   Place the base environment (the `Project.toml` and `Manifest.toml`) and the sysimage file in a globally accessible, read-only directory. This ensures that users cannot modify it. The sysimage should be referenced by setting `JULIA_SYSIMAGE` or by instructing users how to start Julia with the `--sysimage` option pointing to your compiled image.

4. **Use Load Path Stacking to Allow User Customization**:  
   Julia’s load path can include multiple environments. By setting `JULIA_LOAD_PATH` to start with the base environment’s path, users will, by default, get `FUSE` and all its dependencies from the stable, sysimage-backed environment. For example:
   ```sh
   export JULIA_LOAD_PATH="/path/to/shared/env:@:"
   ```
   This puts the shared environment first in the load path. The `@` and `:` entries allow users to create their own local environments (for example, in `~/.julia/environments`) that stack on top of the base environment.

5. **Users Add Packages in Their Own Environment**:  
   Since the shared environment is read-only and stable, users cannot modify it, which is by design. However, they can activate their own local environment (e.g., `Pkg.activate("~/.julia/environments/myenv")`) and add or change packages there. These personal environments will be layered on top of the base environment, allowing the user to override or add packages without touching the shared environment.

   Changes in the user’s personal environment won’t affect the base environment or the sysimage. Packages not included in the base environment won’t gain the startup speed benefits of the sysimage, but everything provided by the base environment will still be fast.

**Result**:  
With this approach, you lock down and precompile a known-good environment containing `FUSE` and its dependencies. All cluster users benefit from fast load times for those packages, while still retaining the freedom to customize their own environments by layering them above the shared base environment. This prevents version conflicts or accidental breakage in the public environment, ensures reproducibility, and gives users flexibility without granting them permission to alter the public base environment.

**Comment by bclyons12** [comment]
We now have a script for creating the FUSE sysimage and module one Omega: https://github.com/ProjectTorreyPines/FUSE.jl/tree/master/deploy/omega

`module load fuse` works on Omega.

**Comment by bclyons12** [comment]
Documenting for future reference. I've occasionally gotten the error below when compiling a sysimage on the Omega worker node. [Suspicion is that it runs out of memory](https://github.com/JuliaLang/PackageCompiler.jl/issues/670), so I'm going to try again with more memory and confirm.
```
✖ [37m:23s] PackageCompiler: compiling incremental system image
ERROR: LoadError: failed process: Process(`/fusion/projects/codes/julia/julia-1.11.3/bin/julia --color=yes --startup-file=no --pkgimages=no '--cpu-target=generic;cascadelake,-xsaveopt,-rdrnd,clone_all;znver2,-xsaveopt,-rdrnd,clone_all' --sysimage=/fusion/projects/codes/julia/julia-1.11.3/lib/julia/sys.so --project=/fusion/projects/codes/julia/fuse/environments/v0.6.0 --output-o=/tmp/jl_34ZIdGZslk-o.a /tmp/jl_lqFQtGretI`, ProcessSignaled(9)) [0]

Stacktrace:
  [1] pipeline_error
    @ ./process.jl:598 [inlined]
  [2] run(::Cmd; wait::Bool)
    @ Base ./process.jl:513
  [3] run
    @ ./process.jl:510 [inlined]
  [4] #20
    @ /fusion/projects/codes/julia/fuse/environments/v0.6.0/.julia/packages/PackageCompiler/UbaS4/ext/TerminalSpinners.jl:157 [inlined]
  [5] spin(f::PackageCompiler.var"#20#22"{Cmd}, s::PackageCompiler.TerminalSpinners.Spinner{Base.TTY})
    @ PackageCompiler.TerminalSpinners /fusion/projects/codes/julia/fuse/environments/v0.6.0/.julia/packages/PackageCompiler/UbaS4/ext/TerminalSpinners.jl:164
  [6] macro expansion
    @ /fusion/projects/codes/julia/fuse/environments/v0.6.0/.julia/packages/PackageCompiler/UbaS4/ext/TerminalSpinners.jl:157 [inlined]
  [7] create_sysimg_object_file(object_file::String, packages::Vector{String}, packages_sysimg::Set{Base.PkgId}; project::String, base_sysimage::String, precompile_execution_file::Vector{String}, precompile_statements_file::Vector{String}, cpu_target::String, script::Nothing, sysimage_build_args::Cmd, extra_precompiles::String, incremental::Bool, import_into_main::Bool)
    @ PackageCompiler /fusion/projects/codes/julia/fuse/environments/v0.6.0/.julia/packages/PackageCompiler/UbaS4/src/PackageCompiler.jl:130
  [8] create_sysimg_object_file
    @ /fusion/projects/codes/julia/fuse/environments/v0.6.0/.julia/packages/PackageCompiler/UbaS4/src/PackageCompiler.jl:319 [inlined]
  [9] create_sysimage(packages::Vector{String}; sysimage_path::String, project::String, precompile_execution_file::String, precompile_statements_file::Vector{String}, incremental::Bool, filter_stdlibs::Bool, cpu_target::String, script::Nothing, sysimage_build_args::Cmd, include_transitive_dependencies::Bool, base_sysimage::Nothing, julia_init_c_file::Nothing, julia_init_h_file::Nothing, version::Nothing, soname::Nothing, compat_level::String, extra_precompiles::String, import_into_main::Bool)
    @ PackageCompiler /fusion/projects/codes/julia/fuse/environments/v0.6.0/.julia/packages/PackageCompiler/UbaS4/src/PackageCompiler.jl:639
 [10] top-level scope
    @ ~/src/FUSE.jl/deploy/omega/install_fuse_environment.jl:60
in expression starting at /home/lyonsbc/src/FUSE.jl/deploy/omega/install_fuse_environment.jl:60
```
